Repository AY2223S2-CS2103-F10-4/tp, pull requests merged in 2023-03, with the labels that each got.

#24 Modified help and edit features.
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/BusinessSize.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: enhancement

#39 Make changes to UserGuide and ReadME
  README.md
  bin/main/seedu/address/logic/commands/ClearCommand.class
  bin/main/seedu/address/logic/commands/EditCommand$EditPersonDescriptor.class
  bin/main/seedu/address/logic/commands/EditCommand.class
  bin/main/seedu/address/logic/commands/ExitCommand.class
  bin/main/seedu/address/logic/commands/ListCommand.class
  bin/main/seedu/address/logic/parser/AddCommandParser.class
  bin/main/seedu/address/logic/parser/CliSyntax.class
  bin/main/seedu/address/logic/parser/EditCommandParser.class
  bin/main/seedu/address/logic/parser/ParserUtil.class
  bin/main/seedu/address/model/person/BusinessSize.class
  bin/main/seedu/address/model/person/Person.class
  bin/main/seedu/address/model/util/SampleDataUtil.class
  bin/main/seedu/address/storage/JsonAdaptedPerson.class
  bin/main/seedu/address/ui/HelpWindow.class
  bin/main/seedu/address/ui/PersonCard.class
  bin/test/seedu/address/logic/commands/ExitCommandTest.class
  bin/test/seedu/address/storage/JsonAdaptedPersonTest.class
  bin/test/seedu/address/testutil/EditPersonDescriptorBuilder.class
  bin/test/seedu/address/testutil/PersonBuilder.class
  bin/test/seedu/address/testutil/PersonUtil.class
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
  src/main/java/seedu/address/logic/commands/ClearCommand.java
Labels: documentation

#83 Change sort command to take in arguments, trim arguments for add command
  src/main/java/seedu/address/logic/commands/SortAscCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/SortDescCommand.java
  src/main/java/seedu/address/logic/commands/SortNameCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/BusinessSize.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Priority.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortAscCommandTest.java
  src/test/java/seedu/address/logic/commands/SortDescCommandTest.java
  src/test/java/seedu/address/logic/commands/SortNameCommandTest.java
Labels: priority.High

#86 Fix sort by size bug parsing whitespaces, fix command words case-inse…
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/person/BusinessSize.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/SummaryWindow.fxml
Labels: priority.Medium
